"""
cumulant_kernel.py — Central-Moment Two-Relaxation-Rate Collision Kernel
=========================================================================
Originally generated by waam_twin/tools/derive_cumulant.py; manually patched
to apply omega_b independently (regenerate-and-rediff if you rerun the
derivation script).

WHAT THIS IS (be precise in publications):
  D3Q19 collision in central-moment space where the SECOND-ORDER stress
  moments are relaxed with two independent rates — the deviatoric (shear)
  part at omega_s and the trace (bulk) part at omega_b. All higher-order
  moments are projected directly onto their equilibria (equivalent to
  relaxing them at rate 1). This is a two-rate central-moment MRT, NOT a
  full multi-rate MRT with independently tunable energy/ghost modes and
  not a full cumulant operator. With omega_b == omega_s it reduces to SRT
  in central-moment coordinates.
"""

import taichi as ti
from .grid import Q


# Relaxation rates:
#   omega_s  = 1/tau_s  (shear viscosity — deviatoric stress modes)
#   omega_b  = 1/tau_b  (bulk viscosity — trace of the stress tensor)
#   higher-order moments: equilibrated (rate 1)

@ti.kernel
def collide_mrt(
    f_src: ti.template(),
    f_dst: ti.template(),
    rho:   ti.template(),
    ux:    ti.template(),
    uy:    ti.template(),
    uz:    ti.template(),
    Fx:    ti.template(),
    Fy:    ti.template(),
    Fz:    ti.template(),
    f_l:   ti.template(),
    flags: ti.template(),
    EX: ti.template(), EY: ti.template(), EZ: ti.template(),
    W:  ti.template(),
    OPP: ti.template(),
    omega_s:     ti.f32,    # Shear relaxation rate = 1/tau
    omega_b:     ti.f32,    # Bulk  relaxation rate
    C_darcy:     ti.f32,
    FLAG_SOLID:  ti.i32,
    FLAG_GAS:    ti.i32,
    nx: ti.i32, ny: ti.i32, nz: ti.i32,
):
    """
    D3Q19 two-rate collision in the central moment space.

    Deviatoric stress relaxed at omega_s (shear viscosity), stress trace at
    omega_b (bulk viscosity). Density and momentum are conserved exactly.
    Semi-implicit Carman-Kozeny drag is applied to the post-collision u.
    Guo forcing is included for body forces (Marangoni + buoyancy).
    """
    cs2     = 1.0 / 3.0
    inv_cs2 = 3.0
    eps     = 1.0e-6

    for i, j, k in rho:
        if flags[i, j, k] == FLAG_SOLID or flags[i, j, k] == FLAG_GAS:
            continue

        fl = f_l[i, j, k]
        fx = Fx[i, j, k]
        fy = Fy[i, j, k]
        fz = Fz[i, j, k]

        # ── Load 19 distributions into registers ──────────────────────
        _f0 = f_src[0, i, j, k]
        _f1 = f_src[1, i, j, k]
        _f2 = f_src[2, i, j, k]
        _f3 = f_src[3, i, j, k]
        _f4 = f_src[4, i, j, k]
        _f5 = f_src[5, i, j, k]
        _f6 = f_src[6, i, j, k]
        _f7 = f_src[7, i, j, k]
        _f8 = f_src[8, i, j, k]
        _f9 = f_src[9, i, j, k]
        _f10 = f_src[10, i, j, k]
        _f11 = f_src[11, i, j, k]
        _f12 = f_src[12, i, j, k]
        _f13 = f_src[13, i, j, k]
        _f14 = f_src[14, i, j, k]
        _f15 = f_src[15, i, j, k]
        _f16 = f_src[16, i, j, k]
        _f17 = f_src[17, i, j, k]
        _f18 = f_src[18, i, j, k]

        # ── Raw moments ─────────────────────────────────────────────
        _rho = _f0 + _f1 + _f2 + _f3 + _f4 + _f5 + _f6 + _f7 + _f8 + _f9 + _f10 + _f11 + _f12 + _f13 + _f14 + _f15 + _f16 + _f17 + _f18
        _inv_rho = 1.0 / (_rho + eps)
        _jx = _f1 * 1 + _f2 * -1 + _f7 * 1 + _f8 * -1 + _f9 * 1 + _f10 * -1 + _f11 * 1 + _f12 * -1 + _f13 * 1 + _f14 * -1
        _jy = _f3 * 1 + _f4 * -1 + _f7 * 1 + _f8 * -1 + _f9 * -1 + _f10 * 1 + _f15 * 1 + _f16 * -1 + _f17 * 1 + _f18 * -1
        _jz = _f5 * 1 + _f6 * -1 + _f11 * 1 + _f12 * -1 + _f13 * -1 + _f14 * 1 + _f15 * 1 + _f16 * -1 + _f17 * -1 + _f18 * 1

        # ── Velocity (with Guo half-step forcing) ────────────────────
        _ux_raw = (_jx + 0.5 * fx) * _inv_rho
        _uy_raw = (_jy + 0.5 * fy) * _inv_rho
        _uz_raw = (_jz + 0.5 * fz) * _inv_rho

        # ── Semi-implicit Carman-Kozeny ──────────────────────────────
        _ck_d = 1.0 + C_darcy * ((1.0 - fl) ** 2) / (fl ** 3 + eps)
        _ux   = _ux_raw / _ck_d
        _uy   = _uy_raw / _ck_d
        _uz   = _uz_raw / _ck_d

        # ── Central moment (stress tensor) ───────────────────────────
        _Pxx = _f1 * 1 + _f2 * 1 + _f7 * 1 + _f8 * 1 + _f9 * 1 + _f10 * 1 + _f11 * 1 + _f12 * 1 + _f13 * 1 + _f14 * 1
        _Pyy = _f3 * 1 + _f4 * 1 + _f7 * 1 + _f8 * 1 + _f9 * 1 + _f10 * 1 + _f15 * 1 + _f16 * 1 + _f17 * 1 + _f18 * 1
        _Pzz = _f5 * 1 + _f6 * 1 + _f11 * 1 + _f12 * 1 + _f13 * 1 + _f14 * 1 + _f15 * 1 + _f16 * 1 + _f17 * 1 + _f18 * 1
        _Pxy = _f7 * 1  * 1 + _f8 * -1  * -1 + _f9 * 1  * -1 + _f10 * -1  * 1
        _Pxz = _f11 * 1  * 1 + _f12 * -1  * -1 + _f13 * 1  * -1 + _f14 * -1  * 1
        _Pyz = _f15 * 1  * 1 + _f16 * -1  * -1 + _f17 * 1  * -1 + _f18 * -1  * 1

        # Central moment (subtract velocity bias)
        _kxx = _Pxx - _rho * _ux * _ux
        _kyy = _Pyy - _rho * _uy * _uy
        _kzz = _Pzz - _rho * _uz * _uz
        _kxy = _Pxy - _rho * _ux * _uy
        _kxz = _Pxz - _rho * _ux * _uz
        _kyz = _Pyz - _rho * _uy * _uz

        # ── Two-rate relaxation toward equilibrium ───────────────────
        # Split the diagonal stress into trace (bulk, relaxed at omega_b)
        # and deviatoric (shear, relaxed at omega_s) parts.
        # Equilibrium: k_ij_eq = rho * cs² * δ_ij  (off-diag = 0)
        _k_mean = (_kxx + _kyy + _kzz) / 3.0
        _k_mean_p = _k_mean - omega_b * (_k_mean - _rho * cs2)

        _kxx_p = _k_mean_p + (1.0 - omega_s) * (_kxx - _k_mean)
        _kyy_p = _k_mean_p + (1.0 - omega_s) * (_kyy - _k_mean)
        _kzz_p = _k_mean_p + (1.0 - omega_s) * (_kzz - _k_mean)
        _kxy_p = _kxy - omega_s * _kxy   # off-diagonals are purely deviatoric
        _kxz_p = _kxz - omega_s * _kxz
        _kyz_p = _kyz - omega_s * _kyz

        # ── Reconstruct post-collision distributions ─────────────────
        # f_eq(rho, u, k_post) using equilibrium expansion:
        # f_i = w_i * [rho + rho*(e·u)/cs² + rho*(e·u)²/(2cs⁴)
        #              - rho*u²/(2cs²) + K_correction]
        _u2 = _ux*_ux + _uy*_uy + _uz*_uz

        _feq0 = 0.3333333333 * (_rho + _rho * inv_cs2 * (0*_ux + 0*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + 0*_uy + 0*_uz)*(0*_ux + 0*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * (0.0))
        _S0   = 0.3333333333 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + 0*fy + 0*fz) + inv_cs2*inv_cs2*(0*fx + 0*fy + 0*fz)*(0*_ux + 0*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[0, i, j, k] = _feq0 + _S0
        _feq1 = 0.0555555556 * (_rho + _rho * inv_cs2 * (1*_ux + 0*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (1*_ux + 0*_uy + 0*_uz)*(1*_ux + 0*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2))))
        _S1   = 0.0555555556 * (1.0 - 0.5*omega_s) * (inv_cs2*(1*fx + 0*fy + 0*fz) + inv_cs2*inv_cs2*(1*fx + 0*fy + 0*fz)*(1*_ux + 0*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[1, i, j, k] = _feq1 + _S1
        _feq2 = 0.0555555556 * (_rho + _rho * inv_cs2 * (-1*_ux + 0*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (-1*_ux + 0*_uy + 0*_uz)*(-1*_ux + 0*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2))))
        _S2   = 0.0555555556 * (1.0 - 0.5*omega_s) * (inv_cs2*(-1*fx + 0*fy + 0*fz) + inv_cs2*inv_cs2*(-1*fx + 0*fy + 0*fz)*(-1*_ux + 0*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[2, i, j, k] = _feq2 + _S2
        _feq3 = 0.0555555556 * (_rho + _rho * inv_cs2 * (0*_ux + 1*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + 1*_uy + 0*_uz)*(0*_ux + 1*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kyy_p - _rho * cs2))))
        _S3   = 0.0555555556 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + 1*fy + 0*fz) + inv_cs2*inv_cs2*(0*fx + 1*fy + 0*fz)*(0*_ux + 1*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[3, i, j, k] = _feq3 + _S3
        _feq4 = 0.0555555556 * (_rho + _rho * inv_cs2 * (0*_ux + -1*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + -1*_uy + 0*_uz)*(0*_ux + -1*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kyy_p - _rho * cs2))))
        _S4   = 0.0555555556 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + -1*fy + 0*fz) + inv_cs2*inv_cs2*(0*fx + -1*fy + 0*fz)*(0*_ux + -1*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[4, i, j, k] = _feq4 + _S4
        _feq5 = 0.0555555556 * (_rho + _rho * inv_cs2 * (0*_ux + 0*_uy + 1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + 0*_uy + 1*_uz)*(0*_ux + 0*_uy + 1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kzz_p - _rho * cs2))))
        _S5   = 0.0555555556 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + 0*fy + 1*fz) + inv_cs2*inv_cs2*(0*fx + 0*fy + 1*fz)*(0*_ux + 0*_uy + 1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[5, i, j, k] = _feq5 + _S5
        _feq6 = 0.0555555556 * (_rho + _rho * inv_cs2 * (0*_ux + 0*_uy + -1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + 0*_uy + -1*_uz)*(0*_ux + 0*_uy + -1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kzz_p - _rho * cs2))))
        _S6   = 0.0555555556 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + 0*fy + -1*fz) + inv_cs2*inv_cs2*(0*fx + 0*fy + -1*fz)*(0*_ux + 0*_uy + -1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[6, i, j, k] = _feq6 + _S6
        _feq7 = 0.0277777778 * (_rho + _rho * inv_cs2 * (1*_ux + 1*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (1*_ux + 1*_uy + 0*_uz)*(1*_ux + 1*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2)) + (1 * (_kyy_p - _rho * cs2)) + (2*1 * _kxy_p)))
        _S7   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(1*fx + 1*fy + 0*fz) + inv_cs2*inv_cs2*(1*fx + 1*fy + 0*fz)*(1*_ux + 1*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[7, i, j, k] = _feq7 + _S7
        _feq8 = 0.0277777778 * (_rho + _rho * inv_cs2 * (-1*_ux + -1*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (-1*_ux + -1*_uy + 0*_uz)*(-1*_ux + -1*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2)) + (1 * (_kyy_p - _rho * cs2)) + (2*1 * _kxy_p)))
        _S8   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(-1*fx + -1*fy + 0*fz) + inv_cs2*inv_cs2*(-1*fx + -1*fy + 0*fz)*(-1*_ux + -1*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[8, i, j, k] = _feq8 + _S8
        _feq9 = 0.0277777778 * (_rho + _rho * inv_cs2 * (1*_ux + -1*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (1*_ux + -1*_uy + 0*_uz)*(1*_ux + -1*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2)) + (1 * (_kyy_p - _rho * cs2)) + (2*-1 * _kxy_p)))
        _S9   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(1*fx + -1*fy + 0*fz) + inv_cs2*inv_cs2*(1*fx + -1*fy + 0*fz)*(1*_ux + -1*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[9, i, j, k] = _feq9 + _S9
        _feq10 = 0.0277777778 * (_rho + _rho * inv_cs2 * (-1*_ux + 1*_uy + 0*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (-1*_ux + 1*_uy + 0*_uz)*(-1*_ux + 1*_uy + 0*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2)) + (1 * (_kyy_p - _rho * cs2)) + (2*-1 * _kxy_p)))
        _S10   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(-1*fx + 1*fy + 0*fz) + inv_cs2*inv_cs2*(-1*fx + 1*fy + 0*fz)*(-1*_ux + 1*_uy + 0*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[10, i, j, k] = _feq10 + _S10
        _feq11 = 0.0277777778 * (_rho + _rho * inv_cs2 * (1*_ux + 0*_uy + 1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (1*_ux + 0*_uy + 1*_uz)*(1*_ux + 0*_uy + 1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2)) + (1 * (_kzz_p - _rho * cs2)) + (2*1 * _kxz_p)))
        _S11   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(1*fx + 0*fy + 1*fz) + inv_cs2*inv_cs2*(1*fx + 0*fy + 1*fz)*(1*_ux + 0*_uy + 1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[11, i, j, k] = _feq11 + _S11
        _feq12 = 0.0277777778 * (_rho + _rho * inv_cs2 * (-1*_ux + 0*_uy + -1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (-1*_ux + 0*_uy + -1*_uz)*(-1*_ux + 0*_uy + -1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2)) + (1 * (_kzz_p - _rho * cs2)) + (2*1 * _kxz_p)))
        _S12   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(-1*fx + 0*fy + -1*fz) + inv_cs2*inv_cs2*(-1*fx + 0*fy + -1*fz)*(-1*_ux + 0*_uy + -1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[12, i, j, k] = _feq12 + _S12
        _feq13 = 0.0277777778 * (_rho + _rho * inv_cs2 * (1*_ux + 0*_uy + -1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (1*_ux + 0*_uy + -1*_uz)*(1*_ux + 0*_uy + -1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2)) + (1 * (_kzz_p - _rho * cs2)) + (2*-1 * _kxz_p)))
        _S13   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(1*fx + 0*fy + -1*fz) + inv_cs2*inv_cs2*(1*fx + 0*fy + -1*fz)*(1*_ux + 0*_uy + -1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[13, i, j, k] = _feq13 + _S13
        _feq14 = 0.0277777778 * (_rho + _rho * inv_cs2 * (-1*_ux + 0*_uy + 1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (-1*_ux + 0*_uy + 1*_uz)*(-1*_ux + 0*_uy + 1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kxx_p - _rho * cs2)) + (1 * (_kzz_p - _rho * cs2)) + (2*-1 * _kxz_p)))
        _S14   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(-1*fx + 0*fy + 1*fz) + inv_cs2*inv_cs2*(-1*fx + 0*fy + 1*fz)*(-1*_ux + 0*_uy + 1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[14, i, j, k] = _feq14 + _S14
        _feq15 = 0.0277777778 * (_rho + _rho * inv_cs2 * (0*_ux + 1*_uy + 1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + 1*_uy + 1*_uz)*(0*_ux + 1*_uy + 1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kyy_p - _rho * cs2)) + (1 * (_kzz_p - _rho * cs2)) + (2*1 * _kyz_p)))
        _S15   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + 1*fy + 1*fz) + inv_cs2*inv_cs2*(0*fx + 1*fy + 1*fz)*(0*_ux + 1*_uy + 1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[15, i, j, k] = _feq15 + _S15
        _feq16 = 0.0277777778 * (_rho + _rho * inv_cs2 * (0*_ux + -1*_uy + -1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + -1*_uy + -1*_uz)*(0*_ux + -1*_uy + -1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kyy_p - _rho * cs2)) + (1 * (_kzz_p - _rho * cs2)) + (2*1 * _kyz_p)))
        _S16   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + -1*fy + -1*fz) + inv_cs2*inv_cs2*(0*fx + -1*fy + -1*fz)*(0*_ux + -1*_uy + -1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[16, i, j, k] = _feq16 + _S16
        _feq17 = 0.0277777778 * (_rho + _rho * inv_cs2 * (0*_ux + 1*_uy + -1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + 1*_uy + -1*_uz)*(0*_ux + 1*_uy + -1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kyy_p - _rho * cs2)) + (1 * (_kzz_p - _rho * cs2)) + (2*-1 * _kyz_p)))
        _S17   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + 1*fy + -1*fz) + inv_cs2*inv_cs2*(0*fx + 1*fy + -1*fz)*(0*_ux + 1*_uy + -1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[17, i, j, k] = _feq17 + _S17
        _feq18 = 0.0277777778 * (_rho + _rho * inv_cs2 * (0*_ux + -1*_uy + 1*_uz) + _rho * inv_cs2 * inv_cs2 * 0.5 * (0*_ux + -1*_uy + 1*_uz)*(0*_ux + -1*_uy + 1*_uz) - _rho * 0.5 * inv_cs2 * _u2 + 0.5 * inv_cs2 * inv_cs2 * ((1 * (_kyy_p - _rho * cs2)) + (1 * (_kzz_p - _rho * cs2)) + (2*-1 * _kyz_p)))
        _S18   = 0.0277777778 * (1.0 - 0.5*omega_s) * (inv_cs2*(0*fx + -1*fy + 1*fz) + inv_cs2*inv_cs2*(0*fx + -1*fy + 1*fz)*(0*_ux + -1*_uy + 1*_uz) - inv_cs2*(_ux*fx + _uy*fy + _uz*fz))
        f_dst[18, i, j, k] = _feq18 + _S18

        # ── Update macroscopic fields ────────────────────────────────
        rho[i, j, k] = _rho
        ux[i, j, k]  = _ux
        uy[i, j, k]  = _uy
        uz[i, j, k]  = _uz